### ISSUE TITLE
Any way to adjust confidence level?

### ISSUE THREAD

**Issue by markmansur** [BohdanNikoletti/SFaceCompare#17]
Hi, I was wondering if there is any way to get back the confidence level of the model?

Thanks.

**Comment by BohdanNikoletti** [comment]
You have 2 options.
 1) Make a better model) 
 2) Try to tweak some values on [Core](https://github.com/BohdanNikoletti/SameFace) of this pod

**Comment by horrion** [comment]
@markmansur Good news, there is a way to mod the confidence levels: The value "result" [here](https://github.com/BohdanNikoletti/SameFace/blob/develop/SameFace/SFaceCompare.swift) returns a confidence value. The threshold is currently set to 1.0 and as such, is a fixed value. If someone decided to pass this value back when succes is called, we'd be able to access it and use it for our own evaluation. If I find the time to do that I'll submit a PR. I'll also fix the "succes" typo while I'm at it 😂

EDIT: @BohdanNikoletti would you mind reopening this issue since it's clearly not a fixed problem?
